#!/usr/bin/env bash
# Serve and open the codebase knowledge graph — an interactive map of files,
# functions, architecture layers, and a guided tour, generated by the
# understand-anything analyzer into .understand-anything/knowledge-graph.json.
set -euo pipefail

cd "$(dirname "$0")"
PORT="${PORT:-4321}"
GRAPH=".understand-anything/knowledge-graph.json"

if [ ! -f "$GRAPH" ]; then
  echo "No knowledge graph found at $GRAPH." >&2
  echo "Regenerate it with the understand-anything analyzer, then re-run this script." >&2
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 not found — it's used to serve the viewer locally." >&2
  exit 1
fi

URL="http://localhost:$PORT/viewer.html"
echo "Knowledge graph viewer → $URL"

(
  cd .understand-anything
  exec python3 -m http.server "$PORT" --bind 127.0.0.1
) &
SERVER_PID=$!
trap 'kill "$SERVER_PID" 2>/dev/null || true' EXIT

sleep 1
if command -v open >/dev/null 2>&1; then
  open "$URL"
elif command -v xdg-open >/dev/null 2>&1; then
  xdg-open "$URL" >/dev/null 2>&1 || true
else
  echo "Open $URL in your browser."
fi

wait "$SERVER_PID"
